# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    apt-get install terraform
    git clone https://github.com/nemrood/demoterraform.git
    cd ../demoterraform/Azure
    terraform init
    terraform plan
    terraform apply
    displayName: " Terraforming the cloud !"